---
title: "Proietti, Luati, Real Time Estimation in Local Polynomial Regression, with Application to Trend-Cycle Analysis (2008)"
subtitle: "Stage d'application, Ensae"
author: "Alain Quartier-la-Tente"
departement: "Ensae --- 2019-2020 "
division: "16/06/2020"
logo: "img/ensae.png"
logo2: "img/nbb.jpg"
automaticcontents: false
output:
    beamer_presentation:
        template: template.tex
        keep_tex: yes
        theme: TorinoTh
        slide_level: 3
header-includes:
- \usepackage{fontawesome5}
- \usepackage{xspace}
- \usepackage{stmaryrd}
themeoptions: "coding=utf8,language=french"
classoption: 'usepdftitle=false,french'
fontsize: 10pt
---

### Introduction

- Problème récurrent en macroéconomie : étude des points de retournement et évaluations de tendances sous-jacentes \faArrowCircleRight{} méthodes d'extraction du signal

- Problème commun à ces méthodes : fiabilité de l'estimation en fin de période

- Objectif : étude des propriétés des estimations en temps réel par des polynômes locaux


# Polynômes locaux et filtres de Henderson

## Filtres symétriques

### Cas général

On suppose que l'on peut décomposer notre série $y_t=\mu_t+\varepsilon_t$ que $\mu_t$ le signal/tendance et $\varepsilon_t\overset{i.i.d}{\sim}\mathcal N(0,\sigma^2)$.

$\mu_t$ est localement approché par un polynôme de degré $d$ :
$$
\forall j\in j\in\left\llbracket -h,h\right\rrbracket \::\: y_{t+j}=m_{t+j}+\varepsilon_{t+j},\quad m_{t+j}=\sum_{i=0}^{d}\beta_{i}j^{i}
$$
\pause
Pour estimer les coefficients il faut $2h \geq d$, on utilise les moindres carrés pondérés (WLS) en minimisant:
$$
S(\hat{\beta}_{0},\dots,\hat{\beta}_{d})=\sum_{j=-h}^{h}\kappa_{j}(y_{t+j}-\hat{\beta}_{0}-\hat{\beta}_{1}j-\dots-\hat{\beta}_{d}j^{d})^{2}
$$
\pause
L'estimateur est $\hat{\beta}=(X'KX)^{1}X'Ky$ et :
$$
\hat{m}_{t}=\hat\beta_0=w'y=\sum_{j=-h}^{h}w_{j}y_{t-j}
$$
\faArrowCircleRight{} estimation par filtre symétrique.

### Cas général
On montre :
$$
\sum_{j=-h}^{h}w_{j}=1,\quad\forall r\in\left\llbracket 1,d\right\rrbracket :\sum_{j=-h}^{h}j^{r}w_{j}=0
$$
\faArrowCircleRight{} le filtre $w$ conserve les tendance polynomiales de degrés $d$

\pause
Filtre Henderson $d=3$ :
$$
w_{j}=\kappa_{j}\frac{(S_{4}-S_{2}j^{2})}{S_{0}S_{4}-S_{2}^{2}}\text{ avec }S_{r}=\sum_{j=-h}^{h}\kappa_{j}j^{r}
$$
$\kappa_j$ trouvés pour maximiser le *smoothness* ($S=\sum(\nabla^{3}w_{j})^{2}$) :
$$
\kappa_{j}=\left[(h+1)^{2}-j^{2}\right]\left[(h+2)^{2}-j^{2}\right]\left[(h+3)^{2}-j^{2}\right]
$$

## Filtres asymétriques

### Filtres asymétriques

3 approches possibles :

1. \emph{Filtre asymétrique direct} par un polynôme local
calculé sur $(y_{t})_{t\in\left\llbracket n-h,n\right\rrbracket }$

2. Prévision à l'horizon $h$ (ou backast) et utilisation d'un filtre symétrique sur $(\hat{y}_{n+j\mid n})_{j\in\left\llbracket 1,h\right\rrbracket}$

3. Construction d'un filtre minimisant le carré des révisions sous certaines contraintes.

\pause 
#### Propriété
Si on suppose données disponibles jusqu'en $t+q$, $\hat{m}_{t+q\mid n}$ calculés à partir de polynômes de degré $d$ : 
$$\text{méthode 1 }\iff \text{ méthode 2}$$

### Filtres asymétriques directs

- Filtre asymétrique très concentré sur l'observation courante : forte discontinuité entre filtre en temps réel ($q=0$) et lorsque l'on a une observation ($q=1$)  
\faArrowCircleRight{} filtre en temps réel sans biais si série polynôme degré $d$ mais variance élevée
\pause

- $d$ fixé : \faPlusCircle{} longueur du filtre grand ($q\nearrow$), \faPlusCircle{} poids associé à la date courante petit 

- $h$ et $q$ fixés : \faPlusCircle{} $d\nearrow$, \faPlusCircle{} poids associé à la date courante grand


# Classe générale pour filtres asymétriques

## Généralisation

### Généralisation

On considère maintenant :
$$
y=U\gamma+Z\delta+\varepsilon,\quad
\varepsilon\sim\mathcal{N}(0,D)
$$
\textbf{Objectif :} trouver filtre $v$ qui minimise révisions sous certaines contraintes ($U_{p}'v=U'w$, $U=X\implies$ le filtre $v$ reproduit les polynômes de degré $d$)

Équivalent à minimiser :
$$
\varphi(v)=
\underbrace{
  \underbrace{(v-w_{p})'D_{p}(v-w_{p})+
  w_{f}'D_{f}w_{f}}_\text{variance err révision}+
  \underbrace{[\delta'(Z_{p}'v-Z'w)]^{2}}_{biais^2}
}_\text{MSE révisions}+
2l'(U_{p}'v-U'v)
$$
L'erreur de révision est :
$$
\hat{m}_{t\mid t}-\hat{m}_{t}=v'y_{p}-w'y=(v'Z_{p}-w'Z)\delta+v'\varepsilon_{p}-w'\varepsilon
$$


### Cas particuliers

1. Pour $D=K^{-1}$ et $U=X$ (pas de biais)  on retrouve le filtre symétrique.

2. Lorsque le filtre symétrique $w$ est le filtre de Henderson, $U=\begin{pmatrix}1 \\ \vdots\\ 1\end{pmatrix}$, $Z=\begin{pmatrix}-h \\ \vdots\\ h\end{pmatrix}$, $D=\sigma^2 I$ on retrouve les filtres de Musgrave   
$\iff$ coefficients trouvés en faisant prévision par une extrapolation linéaire    
$\delta^{2}/\sigma^{2}$ est lié au ratio $R=\bar{I}/\bar{C}$.

### Idée \bclampe

Relâcher certaines contraintes : arbitrage biais variance. Si $U$ sous ensemble de $X$ : on reproduit polynômes de degré $d^*<d$   
\faArrowCircleRight{} poids mieux distribués, peut réduire la variance \pause

Trois classes de filtres en approximant le filtre symétrique de Henderson :

1. *Linear-Constante* (LC) : $y_t$ linéaire et $v$ conserve constante \faArrowCircleRight{} dépend de $\delta_1^2/\sigma^2$

2. *Quadratic-Linear* (QL) : $y_t$ degré $2$ et $v$ conserve polynôme degré $1$ \faArrowCircleRight{} dépend de $\delta_2^2/\sigma^2$

3. *Cubic-Quadratic* (CQ) : $y_t$ degré $3$ et $v$ conserve polynôme degré $2$ \faArrowCircleRight{} dépend de $\delta_3^2/\sigma^2$

\pause
Plus $\delta_i^2/\sigma^2$ grand, plus filtre donne d'importance aux observations courantes et détectera les points de retournement (timeliness).

$\delta_3^2/\sigma^2=0$ : filtre QL avec $\delta_2^2/\sigma^2\to+\infty$

$\delta_3^2/\sigma^2\to+\infty$ : retrouve filtre asymétriques directs


### Choix des paramètres

Dans les applications, $\delta_i^2/\sigma^2$ trouvé en minimisant les révisions :
$$
MSRE=\frac{1}{n-2h-1}\sum_{t=h+1}^{n-h}(\hat{m}_{t}-\hat{m}_{t\mid t})^{2}
$$
\pause

 - Avec filtre LC biais en cas de point de retournement  
 
 - CQ approche mieux les données mais a une variance plus grande : estimations parfois moins efficaces.
 
 - QL : compromis entre flexibilité et lissage
 
 

### Question en suspens

1. Mieux d'utiliser un filtre asymétrique optimisé qu'un filtre symétrique plus court ?

2. Dans la désaisonnalisation,  que se passe-t-il quand la tendance est mal estimée ? mauvaise décomposition TC+I ?

3. Dans la désaisonnalisation, les filtres sont appliqués sur la séries linéarisées :

  * les points de retournement sont-ils vraiment détectables ? Ne sont-ils pas considérés comme du bruit (correction automatique de X11) ?
  
  * impact d'une mauvaise spécification/estimation lors du pré-ajustement ?
  
4. on considère des tendances déterministes, quid des retournements liés aux tendances stochastiques ?

### Réponses de Jean (1/2)

1. Mieux d'utiliser un filtre asymétrique optimisé qu'un filtre symétrique plus court ?  
\faArrowCircleRight{} la variance devrait augmenter mais a priori pas très différent. Si on prend un filtre asymétrique en minimisant la phase, on devrait trouver des coefficients proches d'un filtre symétrique court. Doit pouvoir se vérifier facilement.

2. Dans la désaisonnalisation,  que se passe-t-il quand la tendance est mal estimée ? mauvaise décomposition TC+I ?  
\faArrowCircleRight{} a priori oui, problème plutôt annexe à la désaisonnalisation. On pourrait tester d'appliquer ces méthodes aux filtres saisonniers, en faisant par exemple une hypothèse de constance des coefficients saisonniers en fin de période.   
Intuition de Jean : ne change pas grand chose

### Réponses de Jean (2/2)

3. \faArrowCircleRight{} modèle ARIMA ne sera pas capable d'estimer le point de retournement, les points de retournement devrait rester visibles.

4. on considère des tendances déterministes, quid des retournements liés aux tendances stochastiques ?  
\faArrowCircleRight{} ces filtres asymétriques ne doivent pas être utilisés de façon automatique mais de façon intelligente, lorsque l'on a des informations extérieures qui nous guident économiquement. Ces filtres devraient bien marcher en cas de retournement mais pas forcément ailleurs, il faudrait le tester.


